### ISSUE TITLE
可否破解 TAPD网站

### ISSUE THREAD

**Issue by nakaDH** [scrapyhub/JSpider#2]
https://www.tapd.cn

**Comment by bytebuff** [comment]
具体是破解这个网站的什么呢？

**Comment by Mrshenxh** [comment]
想要破解TAPD，实现模拟登录，方便后续流程管道建设。需要调用https://www.tapd.cn/cloud_logins/login?site=TAPD&ref=https%3A%2F%2Fwww.tapd.cn%2F43082944%2Fboard%2Fboard%2Findex%3Fboard_id%3D1143082944001000002
重定向url，需要穿相应的dcs_token，encrypt_key，encrypt_iv，password，但是这几个都是加密处理，动态变化的，不知道大佬可否有办法？

**Comment by bytebuff** [comment]
这个没有问题

**Comment by bytebuff** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mrshenxh"<notifications@github.com&gt;; 
发送时间: 2019年9月10日(星期二) 下午4:00
收件人: "scrapyhub/JSpider"<JSpider@noreply.github.com&gt;; 
抄送: "挖掘机小王子"<1960958490@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [scrapyhub/JSpider] 可否破解 TAPD网站 (#2)




想要破解TAPD，实现模拟登录，方便后续流程管道建设。需要调用https://www.tapd.cn/cloud_logins/login?site=TAPD&amp;ref=https%3A%2F%2Fwww.tapd.cn%2F43082944%2Fboard%2Fboard%2Findex%3Fboard_id%3D1143082944001000002重定向url，需要穿相应的dcs_token，encrypt_key，encrypt_iv，password，但是这几个都是加密处理，动态变化的，不知道大佬可否有办法？
