### ISSUE TITLE
大麦网能破解一波否

### ISSUE THREAD

**Issue by yihango** [scrapyhub/JSpider#6]

**Comment by bytebuff** [comment]
破解了大麦网的RSA密码加密

**Comment by 18303060635** [comment]
2814249606跑路狗 别上当

**Comment by bytebuff** [comment]
啥玩意，什么跑路



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月20日(周日) 下午2:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.******@***.***&gt;;
主题: Re: [ScrapingBoot/JSpider] 大麦网能破解一波否 (#6)




 
2814249606跑路狗 别上当
